#!/bin/sh
## Double[][]
java de.unihalle.informatik.Alida.tools.ALDOpRunner MatrixSum \
      matrix='[[1,2,3],[4,5,6]]' sums=-

## wrong input parameter name
java de.unihalle.informatik.Alida.tools.ALDOpRunner MatrixSum \
      mmmatrix='[[1,2,3],[4,5,6]]' sums=-

## wrong array element to parse
java de.unihalle.informatik.Alida.tools.ALDOpRunner MatrixSum \
      matrix='[[1,b,3],[4,5,6]]' sums=-

## Double[]
java de.unihalle.informatik.Alida.tools.ALDOpRunner ALDCalcMeanArray \
	data='[1,2,3]' mean=-

## wrong array element to parse
java de.unihalle.informatik.Alida.tools.ALDOpRunner ALDCalcMeanArray \
	data='[1,x,3]' mean=-

## ExperimentatData1D
java de.unihalle.informatik.Alida.tools.ALDOpRunner SmoothData1D \
	experiment='{ baselineCorrected=false , \
                      description="my experiment" , \
                      data=[1.0,2.0,2.2,3.3,2.0,1.0,1.0,1.0,1.0,2.0,3.3,2.0] }' \
        smoothingMethod=MEAN width=3 \
        smoothedExperiment=-

java de.unihalle.informatik.Alida.tools.ALDOpRunner SmoothData1D \
	experiment=@Exp1-txt  \
        smoothedExperiment=@Exp1-smooth-txt

java de.unihalle.informatik.Alida.tools.ALDOpRunner SmoothData1D \
	experiment='{data=@myexp.data,description="Demo experiment"}' \
        smoothedExperiment=@Exp1-smooth-txt

java de.unihalle.informatik.Alida.tools.ALDOpRunner SmoothData1D \
	experiment='{data=@myexp.data,description="Demo experiment"}' \
        smoothedExperiment='{data=@myexp-smooth.data,description=-}'

java de.unihalle.informatik.Alida.tools.ALDOpRunner DemoWorkflow1D \
	experiment=@Exp1-txt  smoothedExperiment=@Exp1-smooth-txt \
	correctedExtrema=@Exp1-correctedMaxima-txt
