#!/bin/sh
## Double[][]
java de.unihalle.informatik.Alida.tools.ALDOpRunner MatrixSum \
      matrix='[[1,2,3],[4,5,6]]' sums=-

## wrong input parameter name
java de.unihalle.informatik.Alida.tools.ALDOpRunner MatrixSum \
      mmmatrix='[[1,2,3],[4,5,6]]' sums=-

## wrong array element to parse
java de.unihalle.informatik.Alida.tools.ALDOpRunner MatrixSum \
      matrix='[[1,b,3],[4,5,6]]' sums=-

## Double[]
java de.unihalle.informatik.Alida.tools.ALDOpRunner ALDCalcMeanArray \
	data='[1,2,3]' mean=-

## wrong array element to parse
java de.unihalle.informatik.Alida.tools.ALDOpRunner ALDCalcMeanArray \
	data='[1,x,3]' mean=-

