#!/bin/sh
echo '======================================================'
echo '## Double[][]'
java de.unihalle.informatik.Alida.tools.ALDOpRunner MatrixSum \
      matrix='[[1,2,3],[4,5,6]]' sums=-

echo '======================================================'
echo '## wrong input parameter name'
java de.unihalle.informatik.Alida.tools.ALDOpRunner MatrixSum \
      mmmatrix='[[1,2,3],[4,5,6]]' sums=-

echo '======================================================'
echo '## wrong array element to parse'
java de.unihalle.informatik.Alida.tools.ALDOpRunner MatrixSum \
      matrix='[[1,b,3],[4,5,6]]' sums=-

echo '======================================================'
echo '## Double[]'
java de.unihalle.informatik.Alida.tools.ALDOpRunner ALDCalcMeanArray \
	data='[1,2,3]' mean=-

echo '======================================================'
echo '## wrong array element to parse'
java de.unihalle.informatik.Alida.tools.ALDOpRunner ALDCalcMeanArray \
	data='[1,x,3]' mean=-

echo '======================================================'
echo '## ApplyToMatrix'
java \
    de.unihalle.informatik.Alida.tools.ALDOpRunner  ApplyToMatrix \
    matrix='[[1,2,3],[4,5,6]]' \
    summarizeOp='$ALDArrayMean:' summarizeMode=ROW \
    summaries=-

echo '======================================================'
echo '## ExperimentatData1D'
echo '## SmoothData1D'
java de.unihalle.informatik.Alida.tools.ALDOpRunner SmoothData1D \
	experiment='{ baselineCorrected=false , \
                      description="my experiment" , \
                      data=[1.0,2.0,2.2,3.3,2.0,1.0,1.0,1.0,1.0,2.0,3.3,2.0] }' \
        smoothingMethod=MEAN width=3 \
        smoothedExperiment=-

echo '======================================================'
echo '## SmoothData1D: read experiment from file and write to file'
java de.unihalle.informatik.Alida.tools.ALDOpRunner SmoothData1D \
	experiment=@Exp1-txt  \
        smoothedExperiment=@Exp1-smooth-txt

echo '======================================================'
echo '## SmoothData1D: read only data of experiment from file, write experiment to same file as above'
java de.unihalle.informatik.Alida.tools.ALDOpRunner SmoothData1D \
	experiment='{data=@myexp.data,description="Demo experiment"}' \
        smoothedExperiment=@Exp1-smooth-txt

echo '======================================================'
echo '## SmoothData1D: read and write only data of experiment from/to file'
java de.unihalle.informatik.Alida.tools.ALDOpRunner SmoothData1D \
	experiment='{data=@myexp.data,description="Demo experiment"}' \
        smoothedExperiment='{data=@myexp-smooth.data,description=-}'

echo '======================================================'
echo '## DemoWorkflow1D: read and write experiments from/to file'
java de.unihalle.informatik.Alida.tools.ALDOpRunner DemoWorkflow1D \
	experiment=@Exp1-txt  smoothedExperiment=@Exp1-smooth-txt \
	correctedExtrema=@Exp1-correctedMaxima-txt
